name: sura_flutter
description: A flutter package from AsurRaa for widgets and utility functions
version: 0.2.5
homepage: https://github.com/asurraa/sura_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  rxdart: ^0.27.0
  universal_platform: ^1.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
